#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-json-io
Version  : 2.5.2
Release  : 1
URL      : https://github.com/jdereg/json-io/archive/json-io-2.5.2.tar.gz
Source0  : https://github.com/jdereg/json-io/archive/json-io-2.5.2.tar.gz
Source1  : https://repo1.maven.org/maven2/com/cedarsoftware/json-io/2.5.1/json-io-2.5.1.jar
Source2  : https://repo1.maven.org/maven2/com/cedarsoftware/json-io/2.5.1/json-io-2.5.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-json-io-data = %{version}-%{release}

%description
json-io
=======
Perfect Java serialization to and from JSON format (available on Maven Central). To include in your project:
```
<dependency>
<groupId>com.cedarsoftware</groupId>
<artifactId>json-io</artifactId>
<version>2.5.2</version>
</dependency>
```
<a class="coinbase-button" data-code="f5ab44535dc53e81b79e71f123ebdf42" data-button-style="custom_large" data-custom="json-io" href="https://coinbase.com/checkouts/f5ab44535dc53e81b79e71f123ebdf42">Donate Bitcoins</a><script src="https://coinbase.com/assets/button.js" type="text/javascript"></script>

%package data
Summary: data components for the mvn-json-io package.
Group: Data

%description data
data components for the mvn-json-io package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/cedarsoftware/json-io/2.5.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/cedarsoftware/json-io/2.5.1/json-io-2.5.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/cedarsoftware/json-io/2.5.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/cedarsoftware/json-io/2.5.1/json-io-2.5.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/cedarsoftware/json-io/2.5.1/json-io-2.5.1.jar
/usr/share/java/.m2/repository/com/cedarsoftware/json-io/2.5.1/json-io-2.5.1.pom
